
modules:
  - #'buzzer_roll'
  - #'buzzer_spin'
  - 'buzzer_accelerate'
  - #'buzzer_homing'
  - #'buzzer_ramp'
  - #'buzzer_frontrangefinder'
  - #'buzzer_movelaterally'
  - #'buzzer_changealtitude'
  - #'buzzer_inactivity'
  - 'land_toprangefinder'
  - 'retreat_allrangefinders'
  - #'orient_rangefinders'
  - #'approach_frontrangefinder'
  - #'retreat_toprangefinder'
  - #'siderangefinders_changealtitude'
  - #'ballerina'
  - #'homesick'
  - #'push_pull'
  - 'buzzer_quiet_toprangefinder'
  - vader


buzzer_spin:
  - 0  # low frequency, hz
  - 2000  # high frequency, hz
  - 10  # low spin rate, deg/s
  - 2000  # high spin rate, deg/s

buzzer_accelerate:
  - 0  # low frequency, hz
  - 2000  # high frequency, hz
  - 0.1  # low acceleration, m/s^2
  - 3.0  # high acceleration, m/s^2

buzzer_homing:
  - 5  # low frequency, hz
  - 2000  # high frequency, hz
  - 0  # low distance, meters
  - 3  # high distance, meters

buzzer_ramp:
  - 800  # minimum left + right range sum to trigger

buzzer_frontrangefinder:
  - 200 # distance threshold, mm

buzzer_movelaterally:
  - 4000 # sound frequency
  - 0 # duration of sound
  - "right" # direction: choose between "left","right", "forward", "backward"

buzzer_changealtitude:
  - 5000 # sound frequency
  - 0.5 # duration of sound
  - "up" # direction: choose between "up", "down"

buzzer_inactivity:
  - 10     # inactivity_threshold - X seconds of inactivity before the buzzer sounds
  - 7000   # buzzer_frequency - Frequency/pitch of the buzzer sound
  - 1      # buzzer_duration - Duration of the buzzer sound

siderangefinders_changealtitude:
  - 300 # distance threshold, mm
  - 1 # which sensor controls upward motion: can be front: 0, left: 1, back: 2, right: 3
  - 0.1 # upward distance to move, m
  - 3 # which sensor controls downward motion: can be front: 0, left: 1, back: 2, right: 3 
  - 0.2 # downward distance to move, m

land_bottomrangefinder:
  - 200 # land threshold, mm

land_toprangefinder:
  - 100 # land threshold, mm

retreat_toprangefinder:
  - 300 # distance threshold, mm
  - 0.2 # retreat distance, m

approach_frontrangefinder:
  - 500 # high distance threshold, mm
  - 200 # low distance threshold, mm
  - 0.2 # approach distance, m

retreat_allrangefinders:
  - 100 # distance threshold, mm
  - 0.2 # retreat distance, m

orient_rangefinders:
  - 500 # high distance threshold, mm
  - 200 # low distance threshold, mm
  - 90 # turn angle, deg

circleright_topfronttrangefinder_delayed:
  - 3   # time history
  - 500 # distance threshold for front rangefinder
  - 0.3 # circle radius, m

ballerina:
  -360  # turn angle, deg

homesick:
  - 10  # turn angle, deg

push_pull:
  - 500  # detection distance, mm
  - 0.1 # move distance, m

buzzer_quiet_toprangefinder:
  - 40 # turn off buzzer threshold, mm
